#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export GOPATH=$HOME/.go/lib:$HOME/.go/projects
export HOMEBREW_BREWFILE=$HOME/.brew/Brewfile
path=(
	$HOME/.rbenv/bin(N-)
	$HOME/.cargo/bin(N-)
	$HOME/.go/lib/bin(N-)
	$HOME/.go/projects/bin(N-)
	$HOME/.nodebrew/current/bin(N-)
	$path
)

eval "$(rbenv init -)"

alias ocaml='rlwrap ocaml'
alias gcc='/usr/local/bin/gcc'
alias g++='/usr/local/bin/g++'
alias pip-update='pip freeze --local | grep -v '\''^\-e'\'' | cut -d = -f 1 | xargs pip install -U'
alias pip3-update='pip3 freeze --local | grep -v '\''^\-e'\'' | cut -d = -f 1 | xargs pip3 install -U'

# brew-file
if [ -f $(brew --prefix)/etc/brew-wrap ];then
	source $(brew --prefix)/etc/brew-wrap
fi	

# OPAM configuration
. /Users/touyou/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# original function
function all-update() {
    brew update;
    brew upgrade;
    brew cleanup;
    brew cask upgrade;
    pip-update;
    pip3-update
}

# swiftenv
if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi
